# add_newline = true
# command_timeout = 1000
# format = """
# $os$username$directory$all$shell"""
# # right_format = """$all"""
#
# # Drop ugly default prompt characters
# [character]
# disabled = true
# # success_symbol = '[ ](bold green) '
# # error_symbol = '[ ](bold red) '
#
# # ---
#
# [os]
# format = '$symbol'   
# disabled = false
#
# [os.symbols]
# Windows = '[  ](14)'
# Arch = '󰣇'
# Ubuntu = '[  ](208)'
# Macos = '󰀵'
#
# # ---y
# [shell]
# disabled = false
# # format = '[$shell]($style) '
# powershell_indicator = "[ >_](48)"
# zsh_indicator = "[ %](27)"
#
# # Shows the username
# [username]
# style_user = 'white bold'
# style_root = 'black bold'
# format = '[$user]($style) '
# disabled = false
# show_always = true
#
# # Shows the hostname
# [hostname]
# ssh_only = false
# format = 'on [$hostname](24) '
# disabled = true
#
# # Shows current directory
# [directory]
# truncation_length = 1
# truncation_symbol = '…/'
# home_symbol = ' ~'
# read_only_style = '197'
# read_only = '  '
# format = 'at [$path](31)[$read_only]($read_only_style) '
#
# # Shows current git branch
# [git_branch]
# symbol = ' '
# format = 'via [$symbol$branch]($style)'
# # truncation_length = 4
# truncation_symbol = '…/'
# style = '38'
#
# # Shows current git status
# [git_status]
# format = '[$all_status$ahead_behind]($style) '
# style = '44'
# conflicted = '  '
# up_to_date = '  '
# untracked = '  '
# ahead = '⇡${count}'
# diverged = '⇕⇡${ahead_count}⇣${behind_count}'
# behind = '⇣${count}'
# stashed = '  '
# modified = '  '
# staged = '[++\($count\)](green)'
# renamed = ' 襁 '
# deleted = '  '
#
# # Shows kubernetes context and namespace
# [terraform]
# format = "via [ terraform $version]($style) 壟 [$workspace]($style) "
#
# [vagrant]
# format = "via [ vagrant $version]($style) "
#
# [docker_context]
# format = "via [ $context](bold blue) "
#
# [helm]
# format = "via [ $version](bold purple) "
#
# [python]
# symbol = " "
# python_binary = "python3"
# format = "via [${symbol}(${version} )(\\($virtualenv\\) )](51)"
#
# [nodejs]
# format = "via [ $version](bold green) "
# disabled = true
#
# [ruby]
# format = "via [ $version]($style) "
#
# [kubernetes]
# format = 'on [ $context\($namespace\)](bold purple) '
# disabled = false
# # [kubernetes.context_aliases]
# # "clcreative-k8s-staging" = "cl-k8s-staging"
# # "clcreative-k8s-production" = "cl-k8s-prod"

format = """\
  $directory\
  $package\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $python\
  $fill\
  $cmd_duration\
  $username\
  [in](bright white)\
  $os\
  $time\
  $line_break\
  $jobs\
  $shell\
  """

right_format = """\
  $status\
  $memory_usage\
  """

[directory]
truncate_to_repo = true
read_only = " "
truncation_symbol = "…/"

[package]
symbol = " "

[git_branch]
style = 'italic purple'
symbol = " "

[git_commit]
style = "bold white"
tag_symbol = "笠 "
tag_disabled = false

[git_status]
conflicted = "= "
ahead = "⇡×${count} "
behind = "⇣×${count} "
diverged = "${ahead_count}×⇕×${behind_count} "
untracked = "?×${count} "
stashed = "\\$×${count} "
modified = "!×${count} "
staged = "+×${count} "
renamed = "»×${count} "
deleted = "✘×${count} "

[fill]
symbol = " "

[cmd_duration]
format = " took [$duration]($style) "
show_notifications = true
min_time_to_notify = 60_000

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true

[os]
format = '$symbol'
disabled = false

[os.symbols]
Windows = '[  ](14)'
Arch = '[ 󰣇 ](33)'
Ubuntu = '[  ](208)'

[env_var.WSL_DISTRO_NAME]
disabled = true
format = " [$env_value]($style)"
style = "underline purple"

[env_var.MSYSTEM]
disabled = true
format = " [$env_value]($style)"
style = "underline purple"

[shell]
# format = " \\[$indicator]($style)\\"
powershell_indicator = "[>_](48)"
zsh_indicator = "[%](27)"
style = "bold blue"
disabled = false

[battery]
full_symbol = "•"
discharging_symbol = ""
charging_symbol = ""
unknown_symbol = "!"
format = " [$symbol$percentage]($style)"

[[battery.display]]
threshold = 20
style = "italic red"

[[battery.display]]
threshold = 80
style = "italic green"

[[battery.display]]
threshold = 100
style = "italic yellow"

[time]
disabled = false
format = " [$time]($style)"
style = "italic bright-green"

[status]
disabled = false
format = "[$symbol$status]($style)"
symbol = "✕ "

[memory_usage]
format = " $symbol[${ram}]($style)"
threshold = -1
symbol = " "
disabled = false

[aws]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

# [haskell]
# symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
python_binary = "['python', 'python3']"
format = "via [${symbol}(${version} )(\\($virtualenv\\) )](51)"

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
